### ISSUE TITLE
Directional shadow map is broken

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-renderer#136]
See lights example:
<img width="290" alt="screenshot 2019-01-18 at 15 38 49" src="https://user-images.githubusercontent.com/1636460/51396566-3a7e0780-1b37-11e9-8c7a-b0b03e84d140.png">

**Comment by vorg** [comment]
So this is a bug or a feature..

The black rectangle is caused by testing for shadow outside of shadow map. Shadow map here is very tightly focused on the dragon

![screenshot 2019-01-21 at 02 48 26](https://user-images.githubusercontent.com/171001/51443094-4d572e80-1d27-11e9-8965-0b7dc195312b.jpg)

Including geometries that receive shadows to camera view bounding box by replacing https://github.com/pex-gl/pex-renderer/blob/master/index.js#L513 with
```
 return material && (material.castShadows || material.receiveShadows)
```

fixes the problem but not without downsides: shadow map has to cover bigger area causing shadow quality to drop.

![screenshot 2019-01-21 at 02 48 13](https://user-images.githubusercontent.com/171001/51443105-67910c80-1d27-11e9-8035-c7b60b968a86.jpg)

How that's weird because actually i would expect the rectangle not to be there. I fixed exactly that scenario here [Default to fully lit when outside of directional shadow map](https://github.com/pex-gl/pex-renderer/commit/7b6222ca511591fd7901945e98e3ff260b67b375#diff-9109f0062608d41eec30e6415f8684edR67). Investigating...

**Comment by vorg** [comment]
If we include the floor the depth map (far on the image) and the pixel depth (near on the image) are same

<img width="618" alt="screenshot 2019-01-21 at 07 02 55" src="https://user-images.githubusercontent.com/171001/51446233-85c03200-1d52-11e9-8c4a-6d96e22f75d3.png">

If we include the floor but exclude from bounding box the depth map (far on the image) and the pixel depth (near on the image) are similar at 0 but diverge. Depth map is too flat.

<img width="618" alt="screenshot 2019-01-21 at 07 03 21" src="https://user-images.githubusercontent.com/171001/51446234-88228c00-1d52-11e9-9bb5-02d49021ffc2.png">

If we don’t draw the floor into depth map then depthmap has solid background so nothing to compare.

<img width="616" alt="screenshot 2019-01-21 at 07 04 08" src="https://user-images.githubusercontent.com/171001/51446235-8b1d7c80-1d52-11e9-8b16-1830df91511c.png">

Both case 2 & 3 create the rectangle error.

That means something is wrong with near/far.

**Comment by vorg** [comment]
Because we reconstruct depth from depth map (0..1) they resulting distance from camera should be between near..far. The problem is if we don't include floor in the near far for ortho projection matrix our floor will be behind far relatively to the depth map.

Green = within range, red = beyond current light ortho matrix far.

<img width="836" alt="screenshot 2019-01-21 at 08 01 53" src="https://user-images.githubusercontent.com/171001/51446260-e2235180-1d52-11e9-9c4f-6bc81ad38f28.png">

That means if depth map value == far, means there is actually no object at all in the view and no shadow. Adding special case in `shadowing.glsl.js` fixes the problem.

```glsl
float texture2DCompare(sampler2D depthMap, vec2 uv, float compare, float near, float far) {
  float depth = readDepth(depthMap, uv, near, far);
  if (depth >= far) return 1.0;
  return step(compare, depth);
}
```

**Comment by vorg** [comment]
![screenshot 2019-01-21 at 08 08 59](https://user-images.githubusercontent.com/171001/51446318-dedc9580-1d53-11e9-8d0e-2afc567e55a5.jpg)

**Comment by vorg** [comment]
If check is probably not the fastest thing on the planet so it would be good to see how others do it...

**Comment by vorg** [comment]
<img width="668" alt="screenshot 2019-01-24 at 15 48 20" src="https://user-images.githubusercontent.com/171001/51690055-d1433c00-1fef-11e9-91b6-bdbf1a4a61cb.png">

gltf-skin example has the same problem even though it's gone in the lights example

**Comment by dmnsgn** [comment]
Three.js does it with a combination of `all` boolean checks: `bvec2( inFrustum, shadowCoord.z <= 1.0 );`

Apparently because of an issue with &&:
```glsl
// if ( something && something ) breaks ATI OpenGL shader compiler
// if ( all( something, something ) ) using this instead
```

Equivalent to an if check so we're good to go with this method I guess.

From my findings, the depth issue above would be due to an imprecision in the depth calculation so the solution is to add a tolerance factor. I added it as a constant but maybe it should be a uniform or relative to the near/far distance: https://github.com/pex-gl/pex-renderer/compare/25-spot-light-shadow#diff-9109f0062608d41eec30e6415f8684edR11
