### ISSUE TITLE
[gltf] SimpleMorph/MorphPrimitivesTest crash the gltf.js file

### ISSUE THREAD

**Issue by simonharrisco** [pex-gl/pex-renderer#175]
Outputs the following errors to the console
```
morph.js:32 Uncaught TypeError: Cannot read property 'map' of undefined
....

morph.js:18 Uncaught (in promise) TypeError: geom.positions.slice is not a function
```

Link to relevant model:
![image](https://user-images.githubusercontent.com/36566034/55074105-4cc07880-5087-11e9-8b50-0d75d85e4d0b.png)
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SimpleMorph

**Comment by simonharrisco** [comment]
![image](https://user-images.githubusercontent.com/36566034/55148304-d7fd4500-513f-11e9-8f85-bb3027d28048.png)
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MorphPrimitivesTest

Also crashing, renaming issue

**Comment by dmnsgn** [comment]
Due to the fact that `buffer.data` doesn't exists: original data are uploaded to the GPU but never stored in the buffer (I assume for performance reasons)

**Comment by simonharrisco** [comment]
Do you think this is edge case or common?

**Comment by dmnsgn** [comment]
That's an error to fix on our side. Possible solution, passing the original positions data directly from the accessor:
```js
      let morphCmp = renderer.morph({
        // TODO the rest ?
        originalPositions: positionAccessor._data,
        targets: targets,
        weights: mesh.weights
      })
```
What do you think @vorg ?

PS: other issue is that Morph doesn't interpolate yet

**Comment by vorg** [comment]
Given that we store targets it's reasonable to store original positions too. If w read the [morph target spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#morph-targets) it turns out that not only positions but any attribute can be morphed. This is illustrated in  [AnimatedMorphCube](https://github.com/KhronosGroup/glTF-Sample-Models/blob/2eaf839717bba9ceb869dc1819af6e1bb98cfd3a/2.0/AnimatedMorphCube/glTF/AnimatedMorphCube.gltf#L221) example.

This means a more appropriate syntax would be

```javascript
let morphCmp = renderer.morph({
     // TODO the rest ?
     sources: {
        positions: positionAccessor._data,
        normals: ...
     }
     targets: {
        positions: ...,
        normals: ....
     },
     weights: mesh.weights
})
```

https://github.com/pex-gl/pex-renderer/blob/master/examples/gltf-morph.js#L209

**Comment by vorg** [comment]
One more thing is we generate garbage every frame `let newGeom = this.originalPositions.map((pos, i) => {`

We should either modify original positions `geom.positions` or pre-allocate `current` array per each attribute
```javascript
currrent: {
        positions: positionAccessor._data.map((pos) => [...pos]),
        normals: ...
     }
}
````
