### ISSUE TITLE
Remove halo effect in DOF

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#35]
Sharp object leak to the foreground

![screen shot 2017-06-16 at 23 52 11 copy](https://user-images.githubusercontent.com/171001/27247273-e49ab1c2-52ee-11e7-9e67-19123ad94aec.jpg)

Currently DOF is using bilateral blur with sharpness=0 but this causes the halo.

This can be potentially solved e.g. by custom blur with Signed Circle of Confusion (blur radius) idea:
https://bartwronski.com/2014/12/09/designing-a-next-generation-post-effects-pipeline/amp/

**Comment by vorg** [comment]
This can be fixed by porting Tech Garden DOF

**Comment by simonharrisco** [comment]
Problem with this is still resolution dependence right ? I dont think we ever fixed it

**Comment by simonharrisco** [comment]
So old blur has vertical and horizontal pass, so we

pass frame color -> 
output horizontal blur pass to some fbo ->
fbo is fed into vertical pass -> 
outputs frame color

This works well because the ssao is its own incapsulated system. 
Now we have single pass though, and i cant read/write to the same texture. I thought about passing in the texture from the bloom pass straight to the new DOF, but that would require bloom always enabled when DOF is.

Options i see are:
- Write some crazy logic to make sure that the last pass that was done is passed to the dof cmd
- Write empty pass that just write from fbo -> current frame color

Or option 3 i dont know about?

**Comment by vorg** [comment]
Fixed in https://github.com/pex-gl/pex-renderer/pull/222
