### ISSUE TITLE
Improve bloom blur

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#52]
Currently when we spread the glow too much it starts to separate instead of becoming smoother and smoother like here 
http://www.curious-creature.com/2017/08/14/physically-based-rendering-demo/

**Comment by vorg** [comment]
This can be fixed by porting Tech Garden mip map bloom

**Comment by simonharrisco** [comment]
Problem i see here is that we never fixed the resolution dependence

**Comment by simonharrisco** [comment]
Structure question for this one, you have this multipass system each with its own texture, with each iteration requireing a different 'color' for its pass and a different fbo for each size. 
For other multipass things i.e the old bloom you have done the iteration in the index.js as it was the same command over and over however in this one it would be due to needing different colors and different fbo sizes.

I guess my question is, what is more important:
- keeping postprocessing.js JUST about setting up textures and passes and then instead doing the iteration in index.js, somewhat muddying it by having to reference fbos from the postprocessing object
- keeping index.js neater by just calling the a bloom function from postprocessing js, but kinda 'muddying' postprocessing.js by introducing a function that does the multiple passes instead of pure  declaration

**Comment by dmnsgn** [comment]
@simonharrisco Already started here: https://github.com/pex-gl/pex-renderer/tree/post-processing-bloom

**Comment by simonharrisco** [comment]
ah! brilliant thanks
