### ISSUE TITLE
Webpack compatibility

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#59]
As we currently depend on browserify + glslify for inlining shaders does it mean pex-renderer can't be used in webpack projects?

**Comment by vorg** [comment]
@dmnsgn any ideas on that?

**Comment by dmnsgn** [comment]
With Webpack, you'd have to slightly configure your project to handle the transform of `#pragma glslify:`.

There are 2 options :
- use a loader https://github.com/glslify/glslify-loader eg. every file with `frag|vert|glslpickwhatever` extension will be transformed. Not sure this can work out of the box because we're using `glsl(path.join(__dirname, file/path.glsl))`
- use babel with a plugin https://github.com/glslify/babel-plugin-glslify but it is not well maintained

I can try a quick repro case to test that.

**Comment by dmnsgn** [comment]
One problem is that we are relying solely on the node environment and browserify:
- non universal packages like `fs` and `child_process`
- use of `path`
- the old `glsl()` instead of glsl\`\`
- use of `glslify-sync`

That's where a build step with Webpack (or for that matter rollup, parcel) could be beneficial.

**Comment by vorg** [comment]
- `glslify-sync` and by extension `fs` and `child_process` are just legacy code not necessary with glslify@6.0.0
- I use of `path` as [JS Standard Style](https://standardjs.com) has `eslint: no-path-concat` on by default
- use of old `glsl(source or filename)` - it's indeed old and should be replaced with either `glsl.file(filename)` not glsl`` depending use case

**Comment by vorg** [comment]
There is also other solutions
- using glslify only on the dev style and output final to json files or use `brfs` transform like in https://github.com/pex-gl/pex-materials/blob/master/point-sprite-show-colors.js
- writing our own system with future webgl 2 support as i'm mostly using only 2 modules `glsl-gamma` and `glsl-fxaa` ever

**Comment by vorg** [comment]
Solved via 
https://github.com/pex-gl/pex-renderer/pull/67
